version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
      timezone: Etc/UCT
    reviewers:
      - "cloud-security-client-go-team"
    open-pull-requests-limit: 10
