version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
      timezone: Etc/UCT
    reviewers:
      - "liga-oz"
      - "f-blass"
    open-pull-requests-limit: 10
