name: build and test
on:
  push:
    branches:
      - master
  pull_request: { }
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        go: [ '1.15', '1.14' ]
      fail-fast: false

    name: Go ${{ matrix.go }} ${{ matrix.os }} build

    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: |
          go build -v ./...

      - name: Test
        run: |
          go test -v --tags unit ./...