name: build and test
on:
  push:
    branches:
      - master
  pull_request: { }
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        go: [ '1.20', '1.21' ]
      fail-fast: false

    name: Go ${{ matrix.go }} ${{ matrix.os }} build

    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Get dependencies
        run: |
          make get-deps
      - name: Build
        run: |
          make build
      - name: Test
        run: |
          make test
