name: build and test go
on: [ push, pull_request ]
jobs:

  lint:
    runs-on: ubuntu-latest
    name: Go lint

    steps:

      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - run: |
          go get -u -v golang.org/x/lint/golint
          golint ./...

  build:
    strategy:
      matrix:
        goos: [ ubuntu-latest, windows-latest, macos-latest ]
        go: [ '1.15', '1.14' ]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    name: Go ${{ matrix.go }} ${{ matrix.goos }} build

    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: |
          go build -v ./...

      - name: Vet
        run: |
          go vet ./...

      - name: Test
        run: |
          go test -v --tags unit ./...