name: REUSE

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    name: "Compliance Check"
    steps: 
    - uses: actions/checkout@v2
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
