name: REUSE

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  check:
    runs-on: ubuntu-latest
    name: "Compliance Check"
    steps: 
    - uses: actions/checkout@v2
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
