name: REUSE

on:
  push:
    branches:
      - master
  pull_request: { }

jobs:
  check:
    runs-on: ubuntu-latest
    name: "Compliance Check"
    steps: 
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v5
